### ISSUE TITLE
Cannot retrieve ammo.initialSpeed on pre-wipe explosive ammo.

### ISSUE THREAD

**Issue by CodyLyttle** [the-hideout/tarkov-api#119]
Cannot retrieve initial speed on the following items.

Name: "20/70 Elephant killer slug"
Error: "Int cannot represent non-integer value: 620.13"
Index: 157

Name: "20/70  Flechetta Plus"
Error: "Int cannot represent non-integer value: 618.02"
Index: 158

**Comment by Shebuka** [comment]
Fixed with #124
