### ISSUE TITLE
HandbookCategories returns duplicate children.

### ISSUE THREAD

**Issue by CodyLyttle** [the-hideout/tarkov-api#120]
Each child category is returned exactly 275 times.
This issue is not present on equivalent ItemCategories queries.

I've provided two queries highlighting the issue.

- handbookCategories(offset:3, limit:1) {name, children{name}}
   Returns 550 children (2 categories * 275)

- handbookCategories(offset:9, limit:1) {name, children{name}}
   Returns 1100 children (4 categories * 275)

**Comment by Razzmatazzz** [comment]
I believe this was resolved some time ago, but let me know if you still experience it.
