### ISSUE TITLE
Many objectives missing maps

### ISSUE THREAD

**Issue by thaddeus** [the-hideout/tarkov-api#121]
For many objectives that have a specific location or locations associated with the objective, the maps property of the objective is set to an empty array. For now I've overridden this on TT using https://github.com/TarkovTracker/tarkovdata/blob/master/objective_maps.json

This is just a reminder issue for me to deal with after the wipe.

**Comment by GrantBirki** [comment]
@thaddeus Any thoughts or shall we close this bad boy out?
