### ISSUE TITLE
Add failed quests property to Tasks

### ISSUE THREAD

**Issue by thaddeus** [the-hideout/tarkov-api#122]
For tasks where another Task or Tasks are marked as failed when the task is completed, add a property to the Task definition which lists the quests that would be failed. This is currently represented as the "alternatives" property on quests in TD. Additionally, the reputation failure property should be added to represent changes from failures.

**Comment by Razzmatazzz** [comment]
Sorry for the delay on this; I actually didn't see it until just today. I'm bad a checking GH issues. Does #153 look like it will give you what you need?
