### ISSUE TITLE
Add GPS data for TD maps to API

### ISSUE THREAD

**Issue by thaddeus** [the-hideout/tarkov-api#123]
The TD tarkov maps should be moved under tarkov.dev org control, and migrate the GPS data (and associations with task objectives) to the API.

**Comment by Razzmatazzz** [comment]
Thinking about the best way to handle this; it would be ideal if we could use actual in-game coordinates that could then be translated to any map by applying offsets.

**Comment by Razzmatazzz** [comment]
Update to this: I've figured out how to get the map coordinates for quest items, but I'm struggling to get the coordinates for "plant" quests and the boundary coordinates for zones in which certain actions have to be performed. Hoping someone who knows more about this stuff might be able to provide some illumination.
