### ISSUE TITLE
Currency used for x item

### ISSUE THREAD

**Issue by git-egi** [the-hideout/tarkov-api#126]
API returns sellFor array where price is shown but not the currency.
Is there any way I can get the currency of x item from response.

Thanks a lot and very nice work :)

**Comment by Shebuka** [comment]
Just fetch the `currency` with the `price`

```
                sellFor {
                    price
                    currency
                    priceRUB
                }
```

**Comment by git-egi** [comment]
Also I made some front end for a search tool for my personal use that's using your API and would like to share with you guys if you want. Thanks again !

**Comment by git-egi** [comment]
Thanks
