### ISSUE TITLE
Inconsistent naming convention in ItemCategories Key Mechanical data

### ISSUE THREAD

**Issue by Seiju-N** [the-hideout/tarkov-api#154]
Hi there,

I noticed that the naming convention in the Key Mechanical API data is inconsistent with the standard convention used for other items. While other items have spaces between words in the "name" field and hyphens between words in the "normalizedName" field, the Key Mechanical item has no spaces in the "name" field and all letters are in uppercase. This inconsistency may cause confusion and make it difficult to work with the data.

Would it be possible to update the Key Mechanical data to conform to the standard naming convention for consistency and ease of use? This would greatly help in working with the data and prevent confusion.

As English is not my native language, I may not have been able to understand the reason behind this inconsistency. If there is a valid reason for the current naming convention, please let me know so that I can better understand the situation.

Thank you for your attention to this matter. I look forward to your response.

Best regards, Seiju

**Comment by Shebuka** [comment]
Hello @Seiju-N!
I've run a simple items query
```
query {
  items(categoryNames: KeyMechanical) {
    name
    normalizedName
  }
}
```
in [the playground](https://api.tarkov.dev/) with KeyMechanical Category and the data seems to be with our same naming convention:
![Screenshot 2023-02-21 at 09 45 29](https://user-images.githubusercontent.com/10927011/220294555-f58f47af-911c-4344-a84a-953e070d4326.png)

Can you provide an example of what's not working for you?

**Comment by Seiju-N** [comment]
@Shebuka 

Thank you for your reply.

I feel like my perception of the problem is misaligned with yours.
Please check this image.

![image](https://user-images.githubusercontent.com/76099188/220304345-9442a481-906d-4cfe-91de-2ee7d099d84e.png)

Why not 
`{
    "name": "Key mechanical",
    "normalizedName": "key-mechanical"
  }`

**Comment by Shebuka** [comment]
> standard convention used for other **_items_**. While other **_items_** have spaces

I think your original question misses the point that your problem is with **Item Categories**, not with **Items**.

@Razzmatazzz can you look into this?

**Comment by Razzmatazzz** [comment]
A lot of the categories are missing translations in the game files, so we were just using the name given in the items.json as a backup. I've tweaked it so spaces are added between the capital letters.

**Comment by Seiju-N** [comment]
@Shebuka @Razzmatazzz 
I wanted to express my sincere gratitude for your quick response.
Thank you so much.
