### ISSUE TITLE
Issue with query results: Incorrect kappaRequired value for "Capturing Outposts" task

### ISSUE THREAD

**Issue by Seiju-N** [the-hideout/tarkov-api#160]
Hello,

I am experiencing an issue with the query results for the following query.

```
query {
  tasks{
    name
    kappaRequired
  }
}
```

The problem is that for the "Capturing Outposts" task, the kappaRequired value is being returned as true instead of false, which is incorrect.

![image](https://user-images.githubusercontent.com/76099188/226163416-29066481-7c80-4beb-b94d-654cecb6d4e4.png)

Could you please investigate this issue and let me know if there is a fix for it? Thank you.

**Comment by Razzmatazzz** [comment]
Thanks for reporting! should be fixed now.
