### ISSUE TITLE
Incorrect data being returned in taskRequirements

### ISSUE THREAD

**Issue by Seiju-N** [the-hideout/tarkov-api#178]
Hello,

I've encountered an issue where the returned data seems to be incorrect. When sending the following query:

```graphql
query {
  task(id:"60e71ccb5688f6424c7bfec4"){
    id
    name
    minPlayerLevel
    taskRequirements{
      task{
        name
      }
      status
    }
  }
}
```
I receive this response:
```json
{
  "data": {
    "task": {
      "id": "60e71ccb5688f6424c7bfec4",
      "name": "Trophies",
      "minPlayerLevel": 55,
      "taskRequirements": [
        {
          "task": {
            "name": "The Cleaner"
          },
          "status": [
            "complete"
          ]
        }
      ]
    }
  }
}
```

However, the "taskRequirements" data is outdated and should not be present. The only requirement for unlocking the task should be having a level of 55 or higher.

This issue was discovered when my friend and I checked the in-game data and found that, despite not having completed the Task 'The Cleaner', the Task 'Trophies' is available to us.

Please look into this issue and update the data accordingly. Thank you.

**Comment by Razzmatazzz** [comment]
According to the wiki, it looks like the task The Guide should be the prerequisite task for Trophies. Had you and your friend both completed The Guide?

**Comment by Seiju-N** [comment]
Thank you for your response. To clarify, both my friend and I are at level 55 or above, but we have not completed the tasks "The Guide" and "The Cleaner". Despite this, the task "Trophies" is still appearing for us.
