### ISSUE TITLE
Feature request: Current game patch endpoint

### ISSUE THREAD

**Issue by martinmiglio** [the-hideout/tarkov-api#233]
# Feature Description
This is a request to add an endpoint to return the current patch number of the game (i.e. 0.13.5.1.26126) .
A possible source for this is the the [Changelog page](https://escapefromtarkov.fandom.com/wiki/Changelog) on the EFT Wiki or from the [Tarkov Changes site](https://tarkov-changes.com/changes).

## My use case
I'm in the works on creating a site for users to report hideout scav case inputs and returns. I want to be able to track data cross-patches, but be able to filter by certain patch numbers. At this moment, I store the games current minor version (i.e 0.12, 0.13, 0.14), with plans to manually update per patch. It would be preferable to save this value down to the exact patch but it is not feasible to manually record and update this.

I would be open to looking into contributing this endpoint, although I am inexperienced with creating API's in graphql. If someone can guide me to a similar endpoint (if it exists), one which scrapes data from the wiki or tarkov changes, I can give it a shot.

**Comment by GrantBirki** [comment]
@martinmiglio Are you after an endpoint that just returns the _current_ patch and nothing else?

We update the `tarkov.dev` website when each wipe come outs by just adding a new value to the following JSON file that can be viewed here -> https://github.com/the-hideout/tarkov-dev/blob/dff6012feeebe44aa629ef8970b1a4c3421623e2/src/data/wipe-details.json

You could possibly write some code that does the following:

- Fetches this file every so often
- Caches the results of this file somewhere within the system you are building
- Sort the JSON contents by the wipe's start
- Get the most recent value

Hopefully that helps!

It would also be pretty darn easy to include this data somewhere without our GraphQL API if it is not there already.

**Comment by martinmiglio** [comment]
That is absolutely what I'm after, thank you.

Given it is this accessible, I'm not sure its necessary to add to the GraphQL API, although it may make sense for other use cases.
