### ISSUE TITLE
Search by crafts station id

### ISSUE THREAD

**Issue by emilanderss0n** [the-hideout/tarkov-api#317]
Is this possible or do you plan to implement it? I would really like it.

**Comment by Razzmatazzz** [comment]
It's fairly trivial to query crafts (including the station id) and then just filter the response for station id, so I'm not too inclined to add it.

**Comment by emilanderss0n** [comment]
True, I apologize for the question. It was stupid. Beginner in javascript and there were ways to do this.

**Comment by Razzmatazzz** [comment]
You certainly don't have to apologize just for making a feature request! That's what helps the project improve long term.
