### ISSUE TITLE
Translate quests

### ISSUE THREAD

**Issue by frmjar** [the-hideout/tarkov-api#318]
Is there a way to access the quest locales to translate them? There are some quests that are not translated into Spanish for example, and I would like to do it.

**Comment by Razzmatazzz** [comment]
We pull our translations for quests straight from the game's translations. Are there some quests that are translated properly in Spanish in-game but not in the API?

**Comment by frmjar** [comment]
Yesterday, while briefly looking, I did see some missions that were not translated into Spanish, but today I've been searching for an example to show and I haven't found any...
Should I find any in the coming days, I'll attach a screenshot.
