### ISSUE TITLE
Item sellFor field CurrencyItems throwing errors

### ISSUE THREAD

**Issue by MoonTM-GIT** [the-hideout/tarkov-api#54]
Whenever I try to get information about the `currencyItem` of an `ItemPrice`, where the Vendor is not the flea, I got from the `sellFor` field of an Item I get this error: `No item found with id undefined`. It works fine for `ItemPrice`s I got from the `buyFor` field.

That explanation is quite bad, so I attached a little visualization from my debugger, you can easily test that on the playground as well though. Excuse the bad writing, had to do that with my mouse.

Wherever `currencyItem` is null the error occurred, this is the case for elements 0-3 of the `sellFor` list 

![image](https://user-images.githubusercontent.com/66334318/174450320-71c99866-1ff7-4f6f-8da2-8fa9e162681c.png)

**Comment by austinhodak** [comment]
@Razzmatazzz

**Comment by Razzmatazzz** [comment]
This should be fixed now.

**Comment by GrantBirki** [comment]
@Razzmatazzz Which PR closed this issue?

fun fact, you can do this in a PR and it will automatically close the issue when the PR is merged:

```text
resolves: <pr url>
```

**Comment by Razzmatazzz** [comment]
It was resolved by: https://github.com/the-hideout/tarkov-api/pull/56
