### ISSUE TITLE
Trader reset time not accurate

### ISSUE THREAD

**Issue by cloudyaaron** [the-hideout/tarkov-api#73]
Trader reset time not accurate

**Comment by GrantBirki** [comment]
@cloudyaaron Could you please provide some more context for the issue and some examples? This is the first we have heard about the reset times not being accurate and if that is the case, we would like to fix it!

**Comment by cloudyaaron** [comment]
The refreshing time for Jaeger is not correct at the beginning of the wipe. Only Jaeger

**Comment by Razzmatazzz** [comment]
Was this only a problem at the beginning of the wipe, or has it persisted?

When the time isn't correct, what is incorrect about it? Does it indicate a previous reset time that hasn't been updated? Does it indicate a future reset time that doesn't match with what you're seeing in-game?

**Comment by Razzmatazzz** [comment]
Since this doesn't seem to be an ongoing issue, I'm closing this issue. We can re-open if the problem reappears.
