### ISSUE TITLE
Normalized name missing from FleaMarket

### ISSUE THREAD

**Issue by Shebuka** [the-hideout/tarkov-api#78]
In the schema the normalized English name is missing from FleaMarket object

**Comment by GrantBirki** [comment]
I'm not sure if there is a historical reason for why we have `normalizedName: String` excluded from the `FleaMarket` item. If there isn't a good reason for why this is missing today, then I agree and we should absolutely add it! :)

As for the `type` name, I think it is correct being `FleaMarket`. Looking at the schema, many other types have this same case definition. See the examples below:

![image](https://user-images.githubusercontent.com/23362539/178129537-d9b2d3d4-27ea-4f9c-900a-e0005d66535d.png)

![image](https://user-images.githubusercontent.com/23362539/178129541-88c25193-8cf5-4216-a15d-d7434ad4433d.png)

![image](https://user-images.githubusercontent.com/23362539/178129547-973763f8-e767-45da-9c4b-d4d82a4ea650.png)

**Comment by Shebuka** [comment]
It's all caps what is returned in the name field by the API, I see `"name": "БАРАХОЛКА",`

**Comment by Shebuka** [comment]
p.s. Question: if the flea market is _disabled_ do we still get the flea market in `sellto`/`buyfrom `but with `enabled: false`?

**Comment by Razzmatazzz** [comment]
We can add normalizedName to the FleaMarket type. It's missing because normalizedName was a recent addition to the traders and it just wasn't added to the FleaMarket type at the time. 

The flea market name being all in caps is due to the lowercase regex not properly picking up Cyrillic uppercase characters. Is `барахолка` a more appropriate capitalization?

**Comment by Shebuka** [comment]
> The flea market name being all in caps is due to the lowercase regex not properly picking up Cyrillic uppercase characters. Is `барахолка` a more appropriate capitalization?

yes, but with the first letter capital like for all other traders, _Барахолка_

**Comment by Razzmatazzz** [comment]
This is the updated code that's being used to convert the uppercase "FLEA MARKET" to "Flea Market" for all languages:
```
UPPERCASE_STRING.replace(/(?<!\b)([A-ZА-Я])/g, substr => {
    return substr.toLowerCase();
});
```
What it's supposed to do is capture any upper case letters that aren't at the beginning of a word and convert them to lower case. I added `А-Я` to capture Cyrillic upper case characters, but it seems to also be capturing the first upper case letter that's at the beginning of the Russian word.

**Comment by Razzmatazzz** [comment]
I think I figured it out to just return the match if it's at index 1: `Барахолка`

**Comment by Shebuka** [comment]
As we load these names for a particular `lang` can't we simply update the _translation_ to the correct case? (just want to understand how it works)

**Comment by Shebuka** [comment]
I was just testing other languages for `Flea Market` translations and in `cz` it's returned as _Ble**ŠÍ** Trh_ but google returns _Ble**ší** Trh_ (in the first word the last two letters are not capital) and in `fr` _March**É**_, so I suppose the regex is not working for any language other than one that use only basic Latin chars

**Comment by Razzmatazzz** [comment]
This regex isn't being run every time there's an API call; it's being run when item prices are updated and data is uploaded to the cloudflare KVs for the API to use:
https://github.com/the-hideout/tarkov-data-manager/blob/9e5472004784624c75e3ee0b3a83ec1598586623/src/tarkov-data-manager/jobs/update-item-cache.js#L471-L477
