### ISSUE TITLE
lang: zh make no effect.

### ISSUE THREAD

**Issue by AlishaHawkward** [the-hideout/tarkov-api#85]
I tried this code: 
```
query {
  items(lang: zh) {
    id,
    name,
    shortName,
    basePrice,
    avg24hPrice
  }
}
```

But it returns all data with English name, not Chinese name.

**Comment by GrantBirki** [comment]
That is interesting, we certainly have it listed as a support language [here](https://github.com/the-hideout/tarkov-dev/blob/fb685a086307d8d95ed013057f200a59c4e64bea/src/data/supported-languages.json#L10) and that file's contents are sourced directly from the API's list of supported languages... 🤔

**Comment by Razzmatazzz** [comment]
Are items translated to Chinese in-game that are not translated via the API? Theoretically, item names in the API should match what you see in the game for a given language. It appears to me that even though the game has a Chinese localization file, much of it is not actually translated to Chinese.

**Comment by Shebuka** [comment]
I was looking this for `it` lang. There is definetely a discrepancy in what is translated and what not in game, but it appears that we don't have anything translated in the API. In game all bolt action snipers are translated, but only like 70% of shotguns and 20% of carabins.

**Comment by Razzmatazzz** [comment]
The only languages we currently have localization files for are: 
```
cz
de
en
es
fr
hu
ru
tr
zh
```

**Comment by Razzmatazzz** [comment]
Seems like there's an issue with the locale files we're getting.

**Comment by Shebuka** [comment]
Cann we add LanguageCode from the website too?

**Comment by Razzmatazzz** [comment]
Maybe. Sourcing up-to-date translation files has proven somewhat tricky.

**Comment by Razzmatazzz** [comment]
This should be fixed now. Our translations might lag behind the game a bit, but they should be more comprehensive now.
